import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import CourseSelection from "@/components/LandingPage/CourseSelection";
import Fields from "@/components/LandingPage/Fields";
import Founder from "@/components/LandingPage/Founder";
import Instructor from "@/components/LandingPage/Instructor";
import LandingNavbar from "@/components/LandingPage/LandingNavbar";
import LoginSection from "@/components/LandingPage/LoginSection";
import PageNav from "@/components/LandingPage/PageNav";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ backgroundImage: `url("/background.png")` }}>
        {/* navigation bar */}
        <LandingNavbar />
        {/* login section */}
        <LoginSection />
        {/* PageNav */}
        <PageNav />
        {/* fields */}
        <Fields />
        {/* founder */}
        <Founder />
        {/* course selection */}
        <CourseSelection />
        {/* instructor */}
        <Instructor />
        {/* footer */}
        <Footer />
      </main>
    </>
  );
}
